# Use Node 20 as the base image from Docker Hub
FROM node:20
# Set working directory, where your app code will be copied
WORKDIR /app
# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install
# Copy the rest of the app
COPY . .
# Expose the port the app runs on
EXPOSE 3002
# Command to run the app
CMD ["node", "app.js"]